NAME			:= BraiiiiiiinnnzzzZ

SOURCE			:=  \
					source/main.cpp \
					source/Zombie.cpp \
					source/newZombie.cpp \
					source/randomChump.cpp

COMPILE			:= c++ -std=c++98 -Wextra -Werror -Wall $(SOURCE) -o $(NAME)

all:
				$(COMPILE)