NAME			:= BraiiiiiiinnnzzzZ

SOURCE			:=  \
					main.cpp \
					Zombie.cpp \
					newZombie.cpp \
					randomChump.cpp

COMPILE			:= c++ -stdc++98 -Wextra -Werror -Wall $(SOURCE) -o $(NAME)

all:
				$(COMPILE)