NAME			:= Unnecessary_Violence

SOURCE			:=  \
					main.cpp \
					Weapon.cpp \
					HumanA.cpp \
					HumanB.cpp \


COMPILE			:= c++ -std=c++98 -Wextra -Werror -Wall $(SOURCE) -o $(NAME)

all:
				$(COMPILE)