NAME := MyAwesomePhoneBook


SOURCE	+= source/main.cpp

SOURCE	+= source/Contact.cpp

SOURCE	+= source/PhoneBook.cpp

COMPILE := c++ -std=c++98 -Wextra -Werror -Wall $(SOURCE) -o $(NAME)

all:
	$(COMPILE)
