NAME			:= Moar_Brainz!

SOURCE			:=  \
					source/main.cpp \
					source/newZombie.cpp \
					source/randomChump.cpp \
					source/Zombie.cpp \
					source/zombieHorde.cpp


COMPILE			:= c++ -std=c++98 -Wextra -Werror -Wall $(SOURCE) -o $(NAME) 

all:
				$(COMPILE)